import { NotificationItemModel } from "../types/notification";

export const mockNotifications: NotificationItemModel[] = [
  {
    id: 1,
    title: "تکمیل پروفایل",
    message:
      "لطفاً برای افزایش شانس دیده شدن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایه شدن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایه شدن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایه شدن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایه شدن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایه شدن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایه شدن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.ن، پروفایل خود را کامل کنید.",
    sender: {
      id: 101,
      firstName: "سیستم",
      lastName: "",
      avatar: null,
    },
    type: "system",
    isGlobal: true,
    createdAt: "2026-07-24T09:30:00Z",
    expiredAt: null,
    role: "model",
    category: null,
    user: null,
    recipient: {
      id: 1001,
      isSeen: false,
      seenAt: null,
      receiverId: 501,
      createdAt: "2026-07-24T09:30:00Z",
    },
  },
  {
    id: 2,
    title: "فرصت ویژه همکاری",
    message: "یک پروژه جدید مرتبط با دسته‌بندی شما منتشر شده است.",
    sender: {
      id: 102,
      firstName: "ادمین",
      lastName: "پلتفرم",
      avatar: null,
    },
    type: "promotion",
    isGlobal: false,
    createdAt: "2026-07-23T12:00:00Z",
    expiredAt: "2026-08-01T12:00:00Z",
    role: "model",
    category: {
      id: 1,
      name: "فشن",
      slug: "fashion",
    },
    user: null,
    recipient: {
      id: 1002,
      isSeen: true,
      seenAt: "2026-07-23T13:20:00Z",
      receiverId: 501,
      createdAt: "2026-07-23T12:00:00Z",
    },
  },
  {
    id: 3,
    title: "هشدار امنیتی",
    message: "ورود جدیدی به حساب شما شناسایی شده است.",
    sender: {
      id: 101,
      firstName: "سیستم",
      lastName: "",
      avatar: null,
    },
    type: "warning",
    isGlobal: false,
    createdAt: "2026-07-22T18:45:00Z",
    expiredAt: null,
    role: null,
    category: null,
    user: {
      id: 501,
      firstName: "کاربر",
      lastName: "فعلی",
      avatar: null,
    },
    recipient: {
      id: 1003,
      isSeen: false,
      seenAt: null,
      receiverId: 501,
      createdAt: "2026-07-22T18:45:00Z",
    },
  },
  {
    id: 4,
    title: "هشدار امنیتی",
    message: "ورود جدیدی به حساب شما شناسایی شده است.",
    sender: {
      id: 101,
      firstName: "سیستم",
      lastName: "",
      avatar: null,
    },
    type: "info",
    isGlobal: false,
    createdAt: "2026-07-22T18:45:00Z",
    expiredAt: null,
    role: null,
    category: null,
    user: {
      id: 501,
      firstName: "کاربر",
      lastName: "فعلی",
      avatar: null,
    },
    recipient: {
      id: 1003,
      isSeen: false,
      seenAt: null,
      receiverId: 501,
      createdAt: "2026-07-22T18:45:00Z",
    },
  },
];
