# Generated by Django 6.0.3 on 2026-07-28 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_rename_user_notificationrecipient_receiver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_send', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notif',
            field=models.CharField(blank=True, choices=[('lumine', 'لومینه'), ('promotion', 'پروموشن'), ('warning', 'خطر'), ('info', 'اطلاعات')], max_length=25, null=True),
        ),
    ]
