# Generated by Django 6.0.3 on 2026-07-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notification_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type_sender',
            field=models.CharField(blank=True, choices=[('lumine', 'لومینه'), ('user', 'کاربر')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notif',
            field=models.CharField(blank=True, choices=[('success', 'موفق'), ('warning', 'ناموفق'), ('info', 'اطلاعات')], max_length=25, null=True),
        ),
    ]
