# Generated by Django 6.0.3 on 2026-07-27 05:48

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='expires_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
